# Generated by Django 5.2.6 on 2025-12-09 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAllergen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('mild', 'Mild'), ('medium', 'Medium'), ('severe', 'Severe')], default='medium', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('allergy', 'Allergy'), ('intolerance', 'Intolerance'), ('dislike', 'Dislike')], default='allergy', max_length=16)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'unique_together': {('name', 'category')},
            },
        ),
        migrations.CreateModel(
            name='AllergenKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=200)),
                ('allergen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='app_allergens.allergen')),
            ],
        ),
        migrations.CreateModel(
            name='CustomProfileAllergen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('mild', 'Mild'), ('medium', 'Medium'), ('severe', 'Severe')], default='medium', max_length=10)),
                ('allergen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_allergens.allergen')),
            ],
        ),
    ]
