# Generated by Django 5.2.6 on 2025-12-09 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_allergens', '0001_initial'),
        ('app_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customprofileallergen',
            name='custom_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_auth.customprofile'),
        ),
        migrations.AddField(
            model_name='userallergen',
            name='allergen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_allergens.allergen'),
        ),
        migrations.AddField(
            model_name='userallergen',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_auth.userprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='customprofileallergen',
            unique_together={('custom_profile', 'allergen')},
        ),
        migrations.AlterUniqueTogether(
            name='userallergen',
            unique_together={('user_profile', 'allergen')},
        ),
    ]
