# Generated by Django 5.2.6 on 2025-12-10 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_allergens', '0002_initial'),
        ('app_auth', '0002_alter_customprofile_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customprofileallergen',
            name='allergen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customprofile_links', to='app_allergens.allergen'),
        ),
        migrations.AlterField(
            model_name='customprofileallergen',
            name='custom_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_allergens', to='app_auth.customprofile'),
        ),
        migrations.AlterField(
            model_name='userallergen',
            name='allergen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile_links', to='app_allergens.allergen'),
        ),
        migrations.AlterField(
            model_name='userallergen',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_allergens', to='app_auth.userprofile'),
        ),
    ]
