# Generated by Django 5.2.6 on 2025-12-09 12:28

import app_auth.api.utils
import app_auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_allergens', '0001_initial'),
        ('app_groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('allergens', models.ManyToManyField(blank=True, related_name='custom_profiles', through='app_allergens.CustomProfileAllergen', to='app_allergens.allergen')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_profiles', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, related_name='custom_members', to='app_groups.group')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, storage=app_auth.api.utils.OverwriteStorage(), upload_to=app_auth.models.profile_picture_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('allergens', models.ManyToManyField(blank=True, related_name='profiles', through='app_allergens.UserAllergen', to='app_allergens.allergen')),
                ('groups', models.ManyToManyField(blank=True, related_name='members', to='app_groups.group')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
