# Generated by Django 5.2.6 on 2025-12-10 13:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customprofile',
            unique_together={('created_by', 'nickname')},
        ),
    ]
